name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        java-version: [17, 21, 25]
        distribution: ['', '-community']
    env:
      CASK_NAME: 'graalvm${{ matrix.distribution }}-jdk${{ matrix.java-version }}'
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_NO_INSTALL_FROM_API: 1
    name: Test graalvm${{ matrix.distribution }}-jdk${{ matrix.java-version }}.rb on ${{ matrix.os }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Check style
      run: brew style Casks/${CASK_NAME}.rb

    - name: Install cask
      run: brew reinstall --cask --require-sha Casks/${CASK_NAME}.rb

    - name: Validate installation
      run: |
        graalvm_dir=$(find /Library/Java/JavaVirtualMachines/ -maxdepth 1 -type d -name "graalvm-*-${{ matrix.java-version }}" | head -n 1)
        export PATH="${graalvm_dir}/Contents/Home/bin:${PATH}"
        echo "${PATH}"
        which java
        # Ensure the expected `java` version is installed
        java -version 2>&1 | tee java-version.txt
        grep 'version "${{ matrix.java-version }}' java-version.txt
        grep "GraalVM" java-version.txt
        # Ensure GraalVM is picked up by `java_home`
        /usr/libexec/java_home
        /usr/libexec/java_home -V 2>&1 | grep "GraalVM"
